### ISSUE TITLE
nested fold makes for incomprehensible errors

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-effect/effect#65]
since the outer fold captures the inner fold instead of the deeper exception

**Comment by radix** [comment]
can you be more specific? like show some example code and the error you're getting?

**Comment by RonnyPfannschmidt** [comment]
when doing a sequence inside of a sequence, then the outer fold error just shows the inner fold error
and the actual root cause is hidden

i got the code in question on the work computer

its bascially something like 

```
from attr import attributes, attr
from effect import Effect, sync_perform, sync_performer, TypeDispatcher, \
    base_dispatcher, ComposedDispatcher
from effect.fold import sequence

@attributes
class Deep(object):
  n = attr()

@sync_performer
def perform_deep(perfomer, intent):
  print intent
  if intent.n == 0:
    raise AttributeError(   'a')
  return sequence([
    Effect(Deep(n=intent.n-1)),
    Effect(Deep(n=intent.n-1))])


dispatcher = ComposedDispatcher([
    base_dispatcher,
    TypeDispatcher({
        Deep: perform_deep,
    }),
])

sync_perform(dispatcher, Effect(Deep(n=4)))
```

only gives the traceback

```
python test.py
Deep(n=4)
Deep(n=3)
Deep(n=2)
Deep(n=1)
Deep(n=0)
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    sync_perform(dispatcher, Effect(Deep(n=4)))
  File "/home/private/Projects/test_effect/lib/python2.7/site-packages/effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "/home/private/Projects/test_effect/lib/python2.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/home/private/Projects/test_effect/lib/python2.7/site-packages/effect/fold.py", line 57, in <lambda>
    error=lambda e: failed(r, e)))
  File "/home/private/Projects/test_effect/lib/python2.7/site-packages/effect/fold.py", line 53, in failed
    raise FoldError(acc, e)
effect.fold.FoldError: FoldError([], (<class 'effect.fold.FoldError'>, FoldError(), <traceback object at 0x7fb8249e7320>)) -> ORIGINAL TRACEBACK FOLLOWS
  File "/home/private/Projects/test_effect/lib/python2.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/home/private/Projects/test_effect/lib/python2.7/site-packages/effect/fold.py", line 57, in <lambda>
    error=lambda e: failed(r, e)))
  File "/home/private/Projects/test_effect/lib/python2.7/site-packages/effect/fold.py", line 53, in failed
    raise FoldError(acc, e)
```

**Comment by radix** [comment]
Thanks @RonnyPfannschmidt :) fixed in master

**Comment by radix** [comment]
For quick reference here's the new output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "effect/fold.py", line 59, in <lambda>
    error=lambda e: failed(r, e)))
  File "effect/fold.py", line 55, in failed
    raise FoldError(acc, e)
effect.fold.FoldError: <FoldError after accumulating []> Original traceback follows:
Traceback (most recent call last):
  File "effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "effect/fold.py", line 59, in <lambda>
    error=lambda e: failed(r, e)))
  File "effect/fold.py", line 55, in failed
    raise FoldError(acc, e)
FoldError: <FoldError after accumulating []> Original traceback follows:
Traceback (most recent call last):
  File "effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "effect/fold.py", line 59, in <lambda>
    error=lambda e: failed(r, e)))
  File "effect/fold.py", line 55, in failed
    raise FoldError(acc, e)
FoldError: <FoldError after accumulating []> Original traceback follows:
Traceback (most recent call last):
  File "effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "effect/fold.py", line 59, in <lambda>
    error=lambda e: failed(r, e)))
  File "effect/fold.py", line 55, in failed
    raise FoldError(acc, e)
FoldError: <FoldError after accumulating []> Original traceback follows:
Traceback (most recent call last):
  File "effect/_sync.py", line 72, in sync_wrapper
    box.succeed(f(*pass_args))
  File "<stdin>", line 5, in perform_deep
AttributeError: a
```
